# Generated by Django 5.1.5 on 2025-02-26 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emai', models.EmailField(max_length=254)),
                ('Gender', models.CharField(db_default=None, max_length=10, null=True)),
                ('phonenumber', models.IntegerField(max_length=10, null=True)),
                ('country', models.CharField(db_default='India', max_length=20, null=True)),
                ('address_1', models.TextField(null=True)),
                ('address_2', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
