# Generated by Django 5.1.5 on 2025-02-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phonenumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
