# Generated by Django 5.1.5 on 2025-02-26 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0003_alter_userinfo_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='emai',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
