# Generated by Django 5.1.5 on 2025-02-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0005_remove_userinfo_user_alter_userinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(db_default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(db_default=None, max_length=255),
        ),
    ]
