# Generated by Django 5.1.5 on 2025-02-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0006_userinfo_first_name_userinfo_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categoryID',
        ),
    ]
