# Generated by Django 5.1.5 on 2025-02-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0007_rename_category_product_categoryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoryID',
            new_name='category',
        ),
    ]
