# Generated by Django 5.1.5 on 2025-03-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0015_order_order_id_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
