# Generated by Django 5.1.5 on 2025-03-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0016_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='', editable=False, max_length=40, unique=True),
        ),
    ]
