# Generated by Django 5.1.5 on 2025-03-10 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0017_alter_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
